export default {
  flag_quick_travel_modal: "§m§a§p",
  flag_cosmetic_modal: "§c§o§s§m§e§t§i§c",
  flag_vendor_modal: "§v§e§n§d",
  flag_challenge_list_modal: "§l§i§s§t",
  flag_challenge_info_modal: "§i§n§f§o",
  flag_unlock_screen: "§r§e§w§a§r§d",
  flag_override: "§n§o§x",
  flag_subtile: "§z§v",
  locked: "§l§o§c§k",
  image_flag: "§i§m§g",
  content_flag: "§c§o§n§t",
  title_flag: "§t§i",
  locked_flag: "§l§o§c§k",
};
